### ISSUE TITLE
I want to subscribe to the topic "color / yolov4_Spatial_detections" and get the xyz coordinates from "geometry_msgs / Point position"

### ISSUE THREAD

**Issue by yo4hi6o** [luxonis/depthai-ros-examples#32]
I'm writing a program that subscribes to the topic "color / yolov4_Spatial_detections", gets the xyz coordinate value from "geometry_msgs / Point position", gets it with MOVEIT, and does pick and place work.

For now, I'm creating a simple node that subscribes to xyz from "yolov4_Spatial_detections".

```
#include <ros/ros.h>
#include "geometry_msgs/Point.h"
#include <depthai_ros_msgs/SpatialDetection.h>

void clbk(const depthai_ros_msgs::SpatialDetection::ConstPtr& msg) {

    ROS_INFO("position: x=%.2f, y=%.2f", msg->position.x, msg->position.y);
}

int main(int argc, char **argv)
{
  // ROS objects
  ros::init(argc, argv, "tf_example");
  ros::NodeHandle n;
  ros::Subscriber sub = n.subscribe("/yolov4_publisher/color/yolov4_Spatial_detections", 1, clbk);

  ros::spin();

}
```

However, the following error occurs.

```
[ERROR] [1649045029.615433297]: Client [/tf_example] wants topic /yolov4_publisher/color/yolov4_Spatial_detections to have datatype/md5sum [depthai_ros_msgs/SpatialDetection/503c7980b555f0fd79e92d14cb9ac446], but our version has [depthai_ros_msgs/SpatialDetectionArray/f3caf8c6374b91f3a4b93f9610044116]. Dropping connection.
```

The situation was the same even if I deleted the develop and build files and side-compiled to rebuild the workspace.

Can you give me some advice on subscribing to this publisher?

Environment

ubuntu 18.04
Ros  Melodic

Thank you.

**Comment by saching13** [comment]
> void clbk(const depthai_ros_msgs::SpatialDetection::ConstPtr& msg) {

You are using the wrong message. 
You are subscribing to `SpatialDetectionArray` and passing it to `SpatialDetection` Message here.

**Comment by yo4hi6o** [comment]
thank you.

I modified the code as below. 

```
#include <ros/ros.h>
#include "geometry_msgs/Point.h"
#include <depthai_ros_msgs/SpatialDetection.h>
#include <depthai_ros_msgs/SpatialDetectionArray.h>


//void clbk(const depthai_ros_msgs::SpatialDetection::ConstPtr& msg) {
void clbk(const depthai_ros_msgs::SpatialDetectionArray::ConstPtr& msg) {

ROS_INFO("position: x=%.2f, y=%.2f", msg->detections[0].position.x, msg->detections[0].position.y);
   
}

int main(int argc, char **argv)
{
  // ROS objects
  ros::init(argc, argv, "yolov4_subscriber_node");
  ros::NodeHandle n;
  ros::Subscriber sub = n.subscribe("/yolov4_publisher/color/yolov4_Spatial_detections", 1, clbk);

  ros::spin();

}

```
The previous error is gone. However, when I start it, the subscribe node goes down.


Startup procedure
```
roslaunch depthai_examples yolov4_publisher.launch   //T1
 roslaunch depthai_examples yolov4_subscriber.launch  //T2
```
master.log
```
[rosmaster.master][INFO] 2022-04-05 09:39:16,569: publisherUpdate[/yolov4_publisher/color/yolov4_Spatial_detections] -> []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.threadpool][ERROR] 2022-04-05 09:39:16,570: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 860, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 837, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

```

**Comment by saching13** [comment]
I think it is your local connection issue. 
I will create a subscriber example and share it in a day or two.

**Comment by yo4hi6o** [comment]
@saching13 
Thank you for your support. I hope you can share the sample subscribe node.

**Comment by yo4hi6o** [comment]
@saching13
Thankyou.
I didn't know how to subscribe to an array message file.
Based on your tips I was able to solve it with reference to [this issue](https://answers.ros.org/question/60614/how-to-publish-a-vector-of-unknown-length-of-structs-in-ros/). Thank you.

```
[ INFO] [1650183310.524148357]: 
 position:
 x=0.030027
 y=-0.099319
 z=1.019924
```
